### ISSUE TITLE
Path of the fastq

### ISSUE THREAD

**Issue by parsboy66** [vpc-ccg/scTagger#11]
Thanks for a nice tool!

i used sc tagger to read the fastq from the path( there are 1000 fastq in 1 path). 
it seems sctagger needs directly a fastq as input not the path, is that right? and if so, how can i pass a path of fastqs to sctagger?

error: 
IsADirectoryError: [Errno 21] Is a directory: '/fastq_pass'

Thanks
Iman

**Comment by baraaorabi** [comment]
Hello Iman,

I think you have two options.
- The `--reads` takes multiple arguments. So you can pass all FASTQ paths comma separated.
- You can create a UNIX pipe to concatenate all the FASTQs on the fly (without having to use disk storage). This would be somehthing like:

```bash
scTagger.py extract_lr_bc --reads <(cat PATH/TO/FASTQ/DIRECTROY/*.fastq)
```
